<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Browser is Luanching]]>
    </line>
    <line>
      <![CDATA[Login to App]]>
    </line>
    <line>
      <![CDATA[Take Screenshot when test case is failedvalidateUserID]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-04T19:17:22 IST" name="Default suite" finished-at="2022-04-04T19:17:38 IST" duration-ms="15922">
    <groups>
    </groups>
    <test started-at="2022-04-04T19:17:22 IST" name="Default test" finished-at="2022-04-04T19:17:38 IST" duration-ms="15922">
      <class name="TestClasses.Kite_Testclass">
        <test-method is-config="true" signature="browserLuanching()[pri:0, instance:TestClasses.Kite_Testclass@31fa1761]" started-at="2022-04-04T19:17:22 IST" name="browserLuanching" finished-at="2022-04-04T19:17:32 IST" duration-ms="10392" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser is Luanching]]>
            </line>
          </reporter-output>
        </test-method> <!-- browserLuanching -->
        <test-method is-config="true" signature="logintoApp()[pri:0, instance:TestClasses.Kite_Testclass@31fa1761]" started-at="2022-04-04T19:17:32 IST" name="logintoApp" finished-at="2022-04-04T19:17:34 IST" duration-ms="1383" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login to App]]>
            </line>
          </reporter-output>
        </test-method> <!-- logintoApp -->
        <test-method signature="validateUserID()[pri:0, instance:TestClasses.Kite_Testclass@31fa1761]" started-at="2022-04-04T19:17:34 IST" name="validateUserID" finished-at="2022-04-04T19:17:36 IST" duration-ms="2128" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestClasses.Kite_Testclass.validateUserID(Kite_Testclass.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Take Screenshot when test case is failedvalidateUserID]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateUserID -->
        <test-method is-config="true" signature="LogOutfromApp()[pri:0, instance:TestClasses.Kite_Testclass@31fa1761]" started-at="2022-04-04T19:17:36 IST" name="LogOutfromApp" finished-at="2022-04-04T19:17:37 IST" duration-ms="1086" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogOutfromApp -->
        <test-method is-config="true" signature="Browserclosing()[pri:0, instance:TestClasses.Kite_Testclass@31fa1761]" started-at="2022-04-04T19:17:37 IST" name="Browserclosing" finished-at="2022-04-04T19:17:38 IST" duration-ms="302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Browserclosing -->
      </class> <!-- TestClasses.Kite_Testclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
